### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by rrudol** [akai-org/jobs-web#2]
## Description
We need landing page for our project. Should contain short description about product and Click To Action Button. In the future, brand picker would be useful.

**Comment by tomaszgil** [comment]
Homepage desktop design.
![homepage](https://user-images.githubusercontent.com/17861616/42749145-07a3426c-88e3-11e8-8d48-b5552dd4348b.png)

**Comment by tomaszgil** [comment]
Homepage mobile design.
![homepage-mobile](https://user-images.githubusercontent.com/17861616/42749209-3e639e96-88e3-11e8-8a72-a041e3b16f8e.png)

Mobile navigation opened.
![homepage-mobile-menu](https://user-images.githubusercontent.com/17861616/42749228-4c8dbe5c-88e3-11e8-90aa-33358fec1453.png)

**Comment by tomaszgil** [comment]
@rrudol Please provide more explanation about the brand picker - what purpose it should fulfill and how it should function.

**Comment by rrudol** [comment]
Choosing brand means selecting craft like IT, Robotics, or medicine. This will be visible before landing page.

**Comment by tomaszgil** [comment]
I would leave it out for now, maybe create a separate task for that in the future.

**Comment by rrudol** [comment]
Designs approved. Picker moved to separate task: https://github.com/akai-org/jobs-web/issues/16
Related tasks: https://github.com/akai-org/jobs-web/issues/17 https://github.com/akai-org/jobs-web/issues/18
