### ISSUE TITLE
Design offers listing

### ISSUE THREAD

**Issue by rrudol** [akai-org/jobs-web#3]
## Description
View should contain listing of job offer. Listing has filters based on localization, experience and/or other things (**to discuss**). Every job offer should contain job title, company name, sallary and skill level.

**Comment by tomaszgil** [comment]
Listing desktop design.
2 filter already is filled by the user (others are not).
3 position in listing is being hovered.
![listing](https://user-images.githubusercontent.com/17861616/42749809-48449954-88e5-11e8-8d9b-788264075d03.png)

Second filter opened.
![listing-checkbox-opened](https://user-images.githubusercontent.com/17861616/42749934-bafdd2d0-88e5-11e8-9154-6c4846c19f14.png)

**Comment by tomaszgil** [comment]
Listing mobile view.
Filter panel is scrollable horizontally.

![listing-mobile](https://user-images.githubusercontent.com/17861616/42758870-502cbe7e-8905-11e8-9e95-f862edd965ed.png)

**Comment by rrudol** [comment]
Great job @tomaszgil! 
Now lets create tasks for each components visible on designs, then close that issue.

**Comment by rrudol** [comment]
Designs approved, time for development: https://github.com/akai-org/jobs-web/issues/11
