### ISSUE TITLE
Design offer page

### ISSUE THREAD

**Issue by rrudol** [akai-org/jobs-web#5]
## Description
Should contains at least all information included in listing.
Contact form with send CV, apply by linkedin and github url field.

**Comment by tomaszgil** [comment]
@rrudol Would be good to specify the information we want to include about a job position and the company, examples:
https://nofluffjobs.com/job/java-developer-n-rd-hr-4wijbvy9
https://justjoin.it/offers/sinterit-arm-programist

**Comment by rrudol** [comment]
If I were programmer who is searching his first job, I would like to know:
- where is the company office
- how much could I earn
- when can I start
- what should I know
- what can I learn
- what technologies are using (tag cloud?)
- opinions and ratings (I'm not sure if we want it)
- I'd like to apply by form or linkedin button
- how big is company, is it corpo or startup
- short description about company

**Comment by tomaszgil** [comment]
Desktop design. CSS advancement bar is hovered. 
The sidebar form may be fixed to the top while scrolling like here:
https://www.netguru.co/career/front-end-developer

![offer](https://user-images.githubusercontent.com/17861616/42880604-252cb742-8a95-11e8-81f8-3b6f6fe839b9.png)

**Comment by tomaszgil** [comment]
Mobile design.

![offer-mobile](https://user-images.githubusercontent.com/17861616/42882597-8b5415ca-8a99-11e8-870b-eab9ca14d9ca.png)

**Comment by rrudol** [comment]
Desings approved. Related tasks: https://github.com/akai-org/jobs-web/issues/19 https://github.com/akai-org/jobs-web/issues/20
